### ISSUE TITLE
Buggy conversion of SubStr

### ISSUE THREAD

**Issue by GameEntity903** [mmikeww/AHK-v2-script-converter#82] opened 2022-12-29 09:39 UTC
For some reason chint,SubStr(Input, count, 1) became chint,SubStr(Input, (count)<1 ? (count)-1 : (count), 1) in every single appearance in the original script.
In another place, Asc(SubStr(key2, Mod(A_index, StrLen(key2)),1)) - 65 became Ord(SubStr(key2, (Mod(A_index, StrLen(key2)))<1 ? (Mod(A_index, StrLen(key2)))-1 : (Mod(A_index, StrLen(key2))), 1)) - 65.

**Comment by safetycar** [comment] 2022-12-30 15:06
The reason behind the ternary is related to the parameter StartingPos.
In v1, 0 extracts the last character and -1 extracts the two last characters.
In v2, -1 extracts the last character and -2 extracts the two last characters. (0 returns an empty string)

Some parts of the conversions are more like hints, if you know that you weren't using values of 0 or under you could clean it up.

**Comment by mmikeww** [comment] 2022-12-30 15:36
Not a bug. Closing.

**Closed by mmikeww** 2022-12-30 15:36 UTC

**Comment by GameEntity903** [comment] 2023-01-02 06:16
Well, I wasn't using negative numbers till then in SubStr.

**Comment by mmikeww** [comment] 2023-01-02 14:08
> Well, I wasn't using negative numbers till then in SubStr.

In that case, you can simply edit the new conversion appropriately. The converter tries to handle as many possible cases that it can
