### ISSUE TITLE
Nested Gui in wrong location 

### ISSUE THREAD

**Issue by crmarksiv** [mmikeww/AHK-v2-script-converter#102] opened 2023-04-03 21:08 UTC
#SingleInstance force
MsgBox A_AhkVersion
#NoEnv
SendMode Input

;~ gui one ask for sex and age
;~ if sex is male and age > 20
;~    gui two allows them to pick type of drinks
;~  if Beer is picked
;~     offer a free  beer at Joe's Bar

 ; Create GUI 1 to ask for sex and age
Gui, 1:Add, Text, , Sex:
Gui, 1:Add, Radio, vSexMale Checked, Male
Gui, 1:Add, Radio, vSexFemale, Female
Gui, 1:Add, Text, , Age:
Gui, 1:Add, Edit, vAge
Gui, 1:Add, Button, gSubmit, Submit
Gui, 1:Show
return   ;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< missing from chat Gpt
Submit:

Gui,1:Submit  ;,nohide
;If (Sex = "Male" && Age > 20)  ; <<<<<<<<<<<<<<<< chatgpt got this wrong
If (SexMale = 1  && Age > 20)  ;
{
    ; Create GUI 2 to allow selection of drinks
    Gui, 2:Add, Text, , Select your drink:
    Gui, 2:Add, Radio, vDrinkBeer, Beer
    Gui, 2:Add, Radio, vDrinkWine, Wine
    Gui, 2:Add, Button, gDrinkSubmit, Submit
    Gui, 2:Show
}
Return

DrinkSubmit:
Gui, 2:Submit
If (DrinkBeer)
{
    ; Offer free beer at Joe's Bar
    MsgBox, 4, Free Beer Offer, Would you like a free beer at Joe's Bar?
    IfMsgBox Yes
    {
        ; Launch Joe's Bar website or perform any other desired action
       MsgBox " free beer"
     ;Run, http://www.joesbar.com/
    }
}
Gui, 2:Destroy
Return

The second Gui definitions should be with the 1st.

**Comment by Banaanae** [comment] 2024-06-09 09:54
I think the only issue here is that the labels don't convert as global? Which if the case this is a duplicate of #49

**Comment by Banaanae** [comment] 2024-06-16 09:49
This should be fixed now, but if not, please reopen this issue

**Closed** 2024-06-16 09:48 UTC
