### ISSUE TITLE
Replace ByRef by &

### ISSUE THREAD

**Issue by tdalon** [mmikeww/AHK-v2-script-converter#159] opened 2024-04-11 06:39 UTC
Newest AHK v2 does not support ByRef anymore.
It would be nice if the converter would automatically replace ByRef by &.

**Comment by tdalon** [comment] 2024-04-11 07:00
For this as quick fix I have updated the 5Keywords.ahk and added the lines:
` , "ByRef " ,
    "&"
  )`
in the OrderedMap

I am not sure this is the best way to handle since it isn't really a Keyword.

**Comment by Banaanae** [comment] 2024-04-11 11:33
Could you share you code that has the error?
Working for me using the example found on help docs
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/14adac6c-7436-425d-b1ef-df873d3fcc7a)

**Comment by tdalon** [comment] 2024-04-12 07:13
sorry. I have noticed my version is not the latest. I will retry.

**Comment by Banaanae** [comment] 2024-04-12 14:11
> sorry. I have noticed my version is not the latest. I will retry.

As long as your converter has been updated in the last few weeks it should work (I was more wondering if the copy was years old)


But please share your script (or a minimal reproducible version), makes it a lot easier to debug

**Comment by andymbody** [comment] 2024-04-12 15:11
I thought ByRef was already being replaced? I could be wrong.

**Comment by Banaanae** [comment] 2024-04-12 23:38
It is, but it could be possible that the specific code they're using doesn't replace it

**Comment by Banaanae** [comment] 2024-06-15 07:50
Since ByRef already gets replaced I'll close this issue, If the issue still exists feel free to reopen this issue

**Closed by Banaanae** 2024-06-15 07:50 UTC
