### ISSUE TITLE
Does not respect spacing in multiline statements.

### ISSUE THREAD

**Issue by iseahound** [mmikeww/AHK-v2-script-converter#72] opened 2022-04-04 03:00 UTC
None() {
        ; Removes all events.
        return this
            .OnEvent("LeftMouseDown")
            .OnEvent("MiddleMouseDown")
            .OnEvent("RightMouseDown")
    }

becomes 

    None() {
        ; Removes all events.
        return this         .OnEvent("LeftMouseDown")         .OnEvent("MiddleMouseDown")         .OnEvent("RightMouseDown")
    }

I bet somewhere a ```"`n"``` should be ```"`r`n"``` as per windows convention...

**Comment by Banaanae** [comment] 2024-06-13 22:46
I did a mass find and replace of \r with \r\n and it did not fix the issue
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/6dce889d-a166-4a91-a169-272a10d78a9e)
I'm still unsure of a fix, but it likely has something to do with the functions that get the commands to convert
If the root cause can't be found a dirty fix could be done like this
MaskStrings > RegExReplace(Line, "(\s*\.)", "\r\n$1") > RestoreStrings

**Comment by iseahound** [comment] 2024-06-17 02:45
It's probably a missing /r/n then. Possibly somewhere within the tokenization. Thanks for giving this a shot!

**Comment by andymbody** [comment] 2024-06-30 09:47
Should be fixed with PR #219

**Comment by Banaanae** [comment] 2024-07-01 01:48
fixed in #219

**Closed by Banaanae** 2024-07-01 01:48 UTC
