### ISSUE TITLE
WinSetAlwaysOnTop missing parameter

### ISSUE THREAD

**Issue by boardtc** [mmikeww/AHK-v2-script-converter#308] opened 2024-10-31 22:39 UTC
V1:
```
+SPACE::  Winset, Alwaysontop, , A
```

V2 (Converted):
```
+SPACE::[WinSetAlwaysontop](https://www.autohotkey.com/docs/v2/lib/WinSetAlwaysOnTop.htm)(, "A")
```

V2 (Expected):
```
+SPACE::[WinSetAlwaysontop](https://www.autohotkey.com/docs/v2/lib/WinSetAlwaysOnTop.htm)(-1, "A")
```

Note: Difference between [WinSet AlwaysOnTop (v1)](https://www.autohotkey.com/docs/v1/lib/WinSet.htm#AlwaysOnTop) and [WinSetAlwaysOnTop (v2)](https://www.autohotkey.com/docs/v2/lib/WinSetAlwaysOnTop.htm) when omitting the setting parameter: : The former toggles, the latter turns on.

Source: https://www.autohotkey.com/boards/viewtopic.php?f=82&t=134000&p=588883#p588883

**Comment by Banaanae** [comment] 2024-11-01 00:46
Duplicate of #307

**Closed by Banaanae** 2024-11-01 00:46 UTC
