### ISSUE TITLE
Problem registering escaped characters and non escaped characters.

### ISSUE THREAD

**Issue by GameEntity903** [mmikeww/AHK-v2-script-converter#81] opened 2022-12-29 09:30 UTC
Two instances of this have occurred. Once, it was `% becoming `". Another time it was " " becoming "`" `"".

**Comment by dmtr99** [comment] 2023-03-24 18:18
Please provide short examples that demonstrates the error, this makes it easier to debug.

**Comment by Banaanae** [comment] 2024-06-19 04:45
I think the issue is this
V1:
```ahk
MsgBox `% becoming `"
```

V2 (Converted): 
```ahk
MsgBox("`% becoming ``"")
```

V2 (Expected): 
```ahk
MsgBox("`% becoming `"")
```

**Comment by Banaanae** [comment] 2024-06-19 05:09
Committing fix soon

**Comment by Banaanae** [comment] 2024-06-19 06:17
Should be fixed now in https://github.com/mmikeww/AHK-v2-script-converter/commit/d5b0b30e47fb78d94efb79a3d407d1d020a7e9d4, if not feel free to reopen

**Closed by Banaanae** 2024-06-19 06:17 UTC
